### ISSUE TITLE
Sofle with ZMK OLED 128x64 not working

### ISSUE THREAD

**Issue by meirtolpin11** [mctechnology17/zmk-oled-adapter#2]
Hi!

So I tried using the module and compiled a ZMK with the following config - 

```
include:
  - board: nice_nano_v2
    shield: sofle_left oled_adapter_pro_micro_128x64
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: sofle_right oled_adapter_pro_micro_128x64
  - board: nice_nano_v2
    shield: settings_reset
```

The screen that I am using is a 0.96 128*64 screen from AliExpress. 

Unfortunately, it seems not to be working - 

![Image](https://github.com/user-attachments/assets/e2eb2f33-d233-4562-8e4c-e84674d28cf6)

When I plug the 128*32 regular screen, I get image but in strange resolution 

![Image](https://github.com/user-attachments/assets/41bdae7e-3457-4965-8e28-3b0c28269dc7) 

Any ideas about how I can fix this? 

P.S. The [repo](https://github.com/meirtolpin11/Sofle_RGB_ZMK/tree/try-with-64-screen) that I am using 

I will appreciate any help!
